### ISSUE TITLE
Builds have been disabled due to repository inactivity

### ISSUE THREAD

**Issue by jackmawer** [devksingh4/discord-canary#1]
![image](https://user-images.githubusercontent.com/3983253/153713358-2881af6e-09fc-471d-ab38-c372a56ccf90.png)
This has caused the Discord Canary snap to become out of date.
Could you please re-enable the schedule?

**Comment by devksingh4** [comment]
Re-enabled. I have created a GitHub Action to push a new empty commit to a new branch every 60 days so that hopefully the builds keep running.
